# Funding support for this project.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Once the project is set up, uncomment the relevant lines:

# github: [techempower-org]
# open_collective: forage-for-all
# ko_fi: forageforall
# custom: ["https://forage.techempower.org/donate"]
